# coding: utf-8

"""
    BombBomb

    We make it easy to build relationships using simple videos.  # noqa: E501

    OpenAPI spec version: 2.0.831
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bombbomb
from bombbomb.models.prompt_overview import PromptOverview  # noqa: E501
from bombbomb.rest import ApiException


class TestPromptOverview(unittest.TestCase):
    """PromptOverview unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPromptOverview(self):
        """Test PromptOverview"""
        # FIXME: construct object with mandatory attributes with example values
        # model = bombbomb.models.prompt_overview.PromptOverview()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
