# coding: utf-8

"""
    BombBomb

    We make it easy to build relationships using simple videos.  # noqa: E501

    OpenAPI spec version: 2.0.831
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bombbomb
from bombbomb.models.client_group_asset_meta_data import ClientGroupAssetMetaData  # noqa: E501
from bombbomb.rest import ApiException


class TestClientGroupAssetMetaData(unittest.TestCase):
    """ClientGroupAssetMetaData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClientGroupAssetMetaData(self):
        """Test ClientGroupAssetMetaData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = bombbomb.models.client_group_asset_meta_data.ClientGroupAssetMetaData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
