# coding: utf-8

"""
    BombBomb

    We make it easy to build relationships using simple videos.  # noqa: E501

    OpenAPI spec version: 2.0.831
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from bombbomb.models.client_group_asset_meta_data import ClientGroupAssetMetaData  # noqa: F401,E501


class InlineResponse200(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'total_pages': 'int',
        'items': 'list[ClientGroupAssetMetaData]'
    }

    attribute_map = {
        'total_pages': 'totalPages',
        'items': 'items'
    }

    def __init__(self, total_pages=None, items=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger"""  # noqa: E501

        self._total_pages = None
        self._items = None
        self.discriminator = None

        if total_pages is not None:
            self.total_pages = total_pages
        if items is not None:
            self.items = items

    @property
    def total_pages(self):
        """Gets the total_pages of this InlineResponse200.  # noqa: E501


        :return: The total_pages of this InlineResponse200.  # noqa: E501
        :rtype: int
        """
        return self._total_pages

    @total_pages.setter
    def total_pages(self, total_pages):
        """Sets the total_pages of this InlineResponse200.


        :param total_pages: The total_pages of this InlineResponse200.  # noqa: E501
        :type: int
        """

        self._total_pages = total_pages

    @property
    def items(self):
        """Gets the items of this InlineResponse200.  # noqa: E501


        :return: The items of this InlineResponse200.  # noqa: E501
        :rtype: list[ClientGroupAssetMetaData]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this InlineResponse200.


        :param items: The items of this InlineResponse200.  # noqa: E501
        :type: list[ClientGroupAssetMetaData]
        """

        self._items = items

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
