# coding: utf-8

"""
    BombBomb

    We make it easy to build relationships using simple videos.  # noqa: E501

    OpenAPI spec version: 2.0.831
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SignUploadRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'expiration': 'datetime',
        'conditions': 'object'
    }

    attribute_map = {
        'expiration': 'expiration',
        'conditions': 'conditions'
    }

    def __init__(self, expiration=None, conditions=None):  # noqa: E501
        """SignUploadRequest - a model defined in Swagger"""  # noqa: E501

        self._expiration = None
        self._conditions = None
        self.discriminator = None

        if expiration is not None:
            self.expiration = expiration
        if conditions is not None:
            self.conditions = conditions

    @property
    def expiration(self):
        """Gets the expiration of this SignUploadRequest.  # noqa: E501

        when the upload will expire.  # noqa: E501

        :return: The expiration of this SignUploadRequest.  # noqa: E501
        :rtype: datetime
        """
        return self._expiration

    @expiration.setter
    def expiration(self, expiration):
        """Sets the expiration of this SignUploadRequest.

        when the upload will expire.  # noqa: E501

        :param expiration: The expiration of this SignUploadRequest.  # noqa: E501
        :type: datetime
        """

        self._expiration = expiration

    @property
    def conditions(self):
        """Gets the conditions of this SignUploadRequest.  # noqa: E501

        Key/Value object of request conditions.  # noqa: E501

        :return: The conditions of this SignUploadRequest.  # noqa: E501
        :rtype: object
        """
        return self._conditions

    @conditions.setter
    def conditions(self, conditions):
        """Sets the conditions of this SignUploadRequest.

        Key/Value object of request conditions.  # noqa: E501

        :param conditions: The conditions of this SignUploadRequest.  # noqa: E501
        :type: object
        """

        self._conditions = conditions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SignUploadRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
